version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.22
  aws-eks: circleci/aws-eks@2.1.2
  kubernetes: circleci/kubernetes@0.4.0
  slack: circleci/slack@4.4.2 # ref: https://github.com/CircleCI-Public/slack-orb, https://circleci.com/developer/orbs/orb/circleci/slack#usage-examples

jobs:
  test:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - restore_cache: # ref: https://circleci.com/docs/2.0/caching/#restoring-cache
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}

      - run: npm ci

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run lint

      # - run:
      #     name: Jest Tests
      #     command: npm run test

  build-and-push-image:
    executor: aws-cli/default
    parameters:
      reg:
        type: string
        default: "248606629437.dkr.ecr.us-west-2.amazonaws.com"
      repo:
        type: string
      env:
        type: string
        default: "development"
      issuer_server_url:
        type: string
      verifier_server_url:
        type: string
        default: "https://acme-verifier-api.demo.dev-unumid.co"
      prove_issuer_did:
        type: string
        default: "did:unum:f627cae9-fcd8-4776-a921-86605630f6da"
      hv_issuer_did:
        type: string
        default: "did:unum:f6f248f9-8c02-4b05-a9ee-4bcd67c09d57"
      log_rocket_id:
        type: string
        default: "vm6x8i/id-verification-demo-dev"
      holder_app_uuid:
        type: string
      backend_server_url:
        type: string
        default: "https://id-verification-api.demo.dev-unumid.co"
      prove_auth_url:
        type: string
        default: "http://device.staging.payfone.com"
      wallet_client_url:
        type: string
        default: "https://wallet.dev-unumid.co"

    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
      - add_ssh_keys:
          fingerprints:
            - "ae:c4:5c:af:ef:ea:57:12:99:a3:bb:aa:09:e0:57:14"
      - run:
          command: |
            echo Logging in to Amazon ECR...
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            echo Building the Docker image...
            DOCKER_BUILDKIT=1 docker build --ssh github="$HOME/.ssh/id_rsa" \
            --build-arg API_KEY=${DEV_API_KEY} \
            --build-arg ISSUER_SERVER_URL=<< parameters.issuer_server_url >> \
            --build-arg ENV=<< parameters.env >> \
            --build-arg VERIFIER_SERVER_URL=<< parameters.verifier_server_url >> \
            --build-arg PROVE_ISSUER_DID=<< parameters.prove_issuer_did >> \
            --build-arg LOG_ROCKET_ID=<< parameters.log_rocket_id >> \
            --build-arg HOLDER_APP_UUID=<< parameters.holder_app_uuid >> \
            --build-arg BACKEND_SERVER_URL=<< parameters.backend_server_url >> \
            --build-arg PROVE_AUTH_URL=<< parameters.prove_auth_url >> \
            --build-arg WALLET_CLIENT_URL=<< parameters.wallet_client_url >> \
            -t ${CIRCLE_SHA1} .

            docker tag ${CIRCLE_SHA1} << parameters.reg >>/<< parameters.repo >>:dev-latest
            docker tag ${CIRCLE_SHA1} << parameters.reg >>/<< parameters.repo >>:"${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
            echo Pushing the Docker image...
            docker push << parameters.reg >>/<< parameters.repo >>:"${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
            docker push << parameters.reg >>/<< parameters.repo >>:dev-latest
          name: Update container image

  build-and-push-image-test:
    executor: aws-cli/default
    parameters:
      reg:
        type: string
        default: "248606629437.dkr.ecr.us-west-2.amazonaws.com"
      repo:
        type: string
      env:
        type: string
        default: "development"
      issuer_server_url:
        type: string
      verifier_server_url:
        type: string
        default: "https://acme-verifier-api.demo.dev-unumid.co"
      prove_issuer_did:
        type: string
        default: "did:unum:f627cae9-fcd8-4776-a921-86605630f6da"
      hv_issuer_did:
        type: string
        default: "did:unum:f6f248f9-8c02-4b05-a9ee-4bcd67c09d57"
      log_rocket_id:
        type: string
        default: "vm6x8i/id-verification-demo-dev"
      holder_app_uuid:
        type: string
      backend_server_url:
        type: string
        default: "https://id-verification-api.demo.dev-unumid.co"
      prove_auth_url:
        type: string
        default: "http://device.staging.payfone.com"
      wallet_client_url:
        type: string
        default: "https://wallet.dev-unumid.co"

    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
      - add_ssh_keys:
          fingerprints:
            - "ae:c4:5c:af:ef:ea:57:12:99:a3:bb:aa:09:e0:57:14"
      - run:
          command: |
            echo Logging in to Amazon ECR...
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            echo Building the Docker image...
            DOCKER_BUILDKIT=1 docker build --ssh github="$HOME/.ssh/id_rsa" \
            --build-arg API_KEY=${DEV_API_KEY} \
            --build-arg ISSUER_SERVER_URL=<< parameters.issuer_server_url >> \
            --build-arg ENV=<< parameters.env >> \
            --build-arg VERIFIER_SERVER_URL=<< parameters.verifier_server_url >> \
            --build-arg PROVE_ISSUER_DID=<< parameters.prove_issuer_did >> \
            --build-arg LOG_ROCKET_ID=<< parameters.log_rocket_id >> \
            --build-arg HOLDER_APP_UUID=<< parameters.holder_app_uuid >> \
            --build-arg BACKEND_SERVER_URL=<< parameters.backend_server_url >> \
            --build-arg PROVE_AUTH_URL=<< parameters.prove_auth_url >> \
            --build-arg WALLET_CLIENT_URL=<< parameters.wallet_client_url >> \
            -t ${CIRCLE_SHA1} .

            docker tag ${CIRCLE_SHA1} << parameters.reg >>/<< parameters.repo >>:test-latest
            docker tag ${CIRCLE_SHA1} << parameters.reg >>/<< parameters.repo >>:"${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
            echo Pushing the Docker image...
            docker push << parameters.reg >>/<< parameters.repo >>:"${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
            docker push << parameters.reg >>/<< parameters.repo >>:test-latest
          name: Update container image

  build-and-push-image-sandbox:
    executor: aws-cli/default
    parameters:
      reg:
        type: string
        default: "248606629437.dkr.ecr.us-west-2.amazonaws.com"
      repo:
        type: string
      env:
        type: string
        default: "sandbox"
      issuer_server_url:
        type: string
      verifier_server_url:
        type: string
        default: "https://acme-verifier-api.demo.unumid.co"
      prove_issuer_did:
        type: string
        default: "did:unum:94f9fc51-1098-4c98-92a1-ba4bbf5aafb6"
      log_rocket_id:
        type: string
        default: "vm6x8i/id-verification-demo-client-sandbox"
      holder_app_uuid:
        type: string
      backend_server_url:
        type: string
        default: "https://id-verification-api.demo.unumid.co"
      prove_auth_url:
        type: string
        default: "http://device.payfone.com"
      wallet_client_url:
        type: string
        default: "https://wallet.sandbox-unumid.co"

    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
      - add_ssh_keys:
          fingerprints:
            - "ae:c4:5c:af:ef:ea:57:12:99:a3:bb:aa:09:e0:57:14"
      - run:
          command: |
            echo Logging in to Amazon ECR...
            $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            echo Building the Docker image...
            DOCKER_BUILDKIT=1 docker build --ssh github="$HOME/.ssh/id_rsa" \
            --build-arg API_KEY=${DEV_API_KEY} \
            --build-arg ISSUER_SERVER_URL=<< parameters.issuer_server_url >> \
            --build-arg ENV=<< parameters.env >> \
            --build-arg VERIFIER_SERVER_URL=<< parameters.verifier_server_url >> \
            --build-arg PROVE_ISSUER_DID=<< parameters.prove_issuer_did >> \
            --build-arg LOG_ROCKET_ID=<< parameters.log_rocket_id >> \
            --build-arg HOLDER_APP_UUID=<< parameters.holder_app_uuid >> \
            --build-arg BACKEND_SERVER_URL=<< parameters.backend_server_url >> \
            --build-arg PROVE_AUTH_URL=<< parameters.prove_auth_url >> \
            --build-arg WALLET_CLIENT_URL=<< parameters.wallet_client_url >> \
            -t ${CIRCLE_SHA1} .

            docker tag ${CIRCLE_SHA1} << parameters.reg >>/<< parameters.repo >>:sandbox-latest
            docker tag ${CIRCLE_SHA1} << parameters.reg >>/<< parameters.repo >>:sandbox-"${CIRCLE_TAG}"
            echo Pushing the Docker image...
            docker push << parameters.reg >>/<< parameters.repo >>:sandbox-"${CIRCLE_TAG}"
            docker push << parameters.reg >>/<< parameters.repo >>:sandbox-latest
          name: Update container image

  deploy-image:
    docker: # Referencing the python image here, see https://github.com/CircleCI-Public/aws-eks-orb/issues/52#issuecomment-1006838213
    - image: cimg/python:3.10
    parameters:
      cluster-name:
        type: string
        default: "dev-customer-cluster"
      repo:
        type: string
      deployment:
        type: string

    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          install-kubectl: true
          aws-region: ${AWS_REGION}
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl set image deployment/<< parameters.deployment >> << parameters.deployment >>=${AWS_ECR_URL}/<< parameters.repo >>:"${CIRCLE_BRANCH}-${CIRCLE_PREVIOUS_BUILD_NUM}"

            # Check deployment rollout status every 10 seconds (max 10 minutes) until complete.
            # ref: https://www.jeffgeerling.com/blog/2018/updating-kubernetes-deployment-and-waiting-it-roll-out-shell-script
            ATTEMPTS=0
            ROLLOUT_STATUS_CMD="kubectl rollout status deployment/<< parameters.deployment >>"
            until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 60 ]; do
              $ROLLOUT_STATUS_CMD
              ATTEMPTS=$((attempts + 1))
              sleep 10
            done
          name: Deploy container image to dev
      - slack/notify:
          event: fail
          mentions: '@devops-team'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  deploy-image-sandbox:
    docker: # Referencing the python image here, see https://github.com/CircleCI-Public/aws-eks-orb/issues/52#issuecomment-1006838213
    - image: cimg/python:3.10
    parameters:
      cluster-name:
        type: string
        default: "sandbox-customer-cluster"
      repo:
        type: string
      deployment:
        type: string
      namespace:
        type: string
        default: "demos"

    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          install-kubectl: true
          aws-region: ${AWS_REGION}
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl set image deployment/<< parameters.deployment >> << parameters.deployment >>=${AWS_ECR_URL}/<< parameters.repo >>:sandbox-"${CIRCLE_TAG}" -n << parameters.namespace >>

            # Check deployment rollout status every 10 seconds (max 10 minutes) until complete.
            # ref: https://www.jeffgeerling.com/blog/2018/updating-kubernetes-deployment-and-waiting-it-roll-out-shell-script
            ATTEMPTS=0
            ROLLOUT_STATUS_CMD="kubectl rollout status deployment/<< parameters.deployment >> -n << parameters.namespace >>"
            until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 60 ]; do
              $ROLLOUT_STATUS_CMD
              ATTEMPTS=$((attempts + 1))
              sleep 10
            done
          name: Deploy container image to sandbox
      - slack/notify:
          event: fail
          mentions: '@devops-team'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
                - test-circleci
                - sandbox

  build-and-deploy-release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      # Unum Holder
      - build-and-push-image-sandbox:
          name: "build-and-push-id-verification-demo-sandbox"
          requires:
            - test
          context: AWS-Dev
          repo: id-verification-demo-client
          holder_app_uuid: b8820ef7-8ae8-4fa9-9a99-84629b2ea147
          issuer_server_url: https://unum-issuer-api.demo.dev-unumid.co
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - deploy-image-sandbox:
          name: "deploy-id-verification-demo-sandbox"
          context: 
            - AWS-Dev
            - Slack-Context
          requires:
            - build-and-push-id-verification-demo-sandbox
          repo: id-verification-demo-client
          deployment: id-verification-demo-client
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  build-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      
      # Unum Holder
      - build-and-push-image:
          name: "build-and-push-id-verification-demo"
          requires:
            - test
          context: AWS-Dev
          repo: id-verification-demo-client
          holder_app_uuid: 86810c13-47b4-4a2b-ae46-fb13b6a5177a
          issuer_server_url: https://unum-issuer-api.demo.dev-unumid.co
          filters:
            branches:
              only:
                - main

      - deploy-image:
          name: "build-and-push-id-verification-demo"
          context: 
            - AWS-Dev
            - Slack-Context
          repo: id-verification-demo-client
          deployment: id-verification-demo-client
          requires:
            - build-and-push-id-verification-demo
          filters:
            branches:
              only:
                - main

  build-and-deploy-test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - test-circleci

      # Unum Holder
      - build-and-push-image-test:
          name: "build-and-push-id-verification-demo-test"
          requires:
            - test
          context: AWS-Dev
          repo: id-verification-demo-client
          holder_app_uuid: 86810c13-47b4-4a2b-ae46-fb13b6a5177a
          issuer_server_url: https://unum-issuer-api.demo.dev-unumid.co
          filters:
            branches:
              only:
                - test-circleci
      - deploy-image:
          name: "deploy-id-verification-demo-test"
          context: 
            - AWS-Dev
            - Slack-Context
          repo: id-verification-demo-client
          deployment: id-verification-demo-client
          requires:
            - build-and-push-id-verification-demo-test
          filters:
            branches:
              only:
                - test-circleci
